services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - ai-net

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - tools-basic
      - redis
    networks:
      - ai-net
    volumes:
      - ./data/gateway:/app/data

  redis:
    image: redis:7 # 改成我们行里的Credis
    ports:
      - "6379:6379"
    networks:
      - ai-net
    volumes:
      - ./data/redis:/data

  tools-basic:
    build: ./components/tools-basic
    expose:
      - "7001"
    networks:
      - ai-net

  esb:
    build: ./components/esb
    expose:
      - "7002"
    networks:
      - ai-net
    volumes:
      - ./data/esb:/app/data

networks:
  ai-net:
    name: ai-component-net
