services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - ai-net
    volumes:
      - ./data/nginx:/var/log/nginx

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - ai-net
    volumes:
      - ./data/gateway:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_KEY_PREFIX=aihub:gateway

  redis:
    image: redis:7 # 改成我们行里的Credis
    ports:
      - "6379:6379"
    networks:
      - ai-net
    volumes:
      - ./data/redis:/data

  tools-basic:
    build: ./components/tools-basic
    expose:
      - "7001"
    networks:
      - ai-net
    volumes:
      - ./data/tools-basic:/app/data

  esb:
    build: ./components/esb
    expose:
      - "7002"
    networks:
      - ai-net
    volumes:
      - ./data/esb:/app/data

  orchestrator:
    build: ./orchestrator
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_KEY_PREFIX=aihub:orchestrator
      - STAGING_DIR=/app/data/staging
      - AGENTS_BASE_URL=http://agents:7020
    volumes:
      - ./data/orchestrator:/app/data
    networks:
      - ai-net
    ports:
      - "7010:7010"
    depends_on:
      - redis

  agents:
    build: ./agents
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_KEY_PREFIX=aihub:agents
      - STAGING_DIR=/app/data/staging
      - ESB_BASE_URL=http://esb:7002
      - GATEWAY_URL=http://gateway:8000
    volumes:
      - ./data/agents:/app/data
    networks:
      - ai-net
    ports:
      - "7020:7020"
    depends_on:
      - redis
      - esb
      - gateway

networks:
  ai-net:
    name: ai-component-net
