services:
  redis:
    image: redis:7 # 改成我们行里的Credis
    container_name: ai-component-hub-redis
    ports:
      - "6379:6379"
    networks:
      - ai-net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - ai-net

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - tools-basic
    networks:
      - ai-net

  tools-basic:
    build: ./components/tools-basic
    ports:
      - "7001:7001"
    networks:
      - ai-net

  esb:
    build: ./components/esb
    ports:
      - "7002:7002"
    networks:
      - ai-net
    volumes:
      - ./data:/app/data

networks:
  ai-net:
    name: ai-component-net
