services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - ai-net
    volumes:
      - ./data/nginx:/var/log/nginx

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - tools-basic
      - redis
    networks:
      - ai-net
    volumes:
      - ./data/gateway:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_KEY_PREFIX=aihub:gateway

  redis:
    image: redis:7 # 改成我们行里的Credis
    ports:
      - "6379:6379"
    networks:
      - ai-net
    volumes:
      - ./data/redis:/data

  tools-basic:
    build: ./components/tools-basic
    expose:
      - "7001"
    networks:
      - ai-net
    volumes:
      - ./data/tools-basic:/app/data

  esb:
    build: ./components/esb
    expose:
      - "7002"
    networks:
      - ai-net
    volumes:
      - ./data/esb:/app/data

  orchestrator:
    build: ./orchestrator
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_KEY_PREFIX=aihub:orchestrator
      - STAGING_DIR=/app/data/staging
    volumes:
      - ./data/orchestrator:/app/data
    networks:
      - ai-net
    depends_on:
      - redis

networks:
  ai-net:
    name: ai-component-net
